### ISSUE TITLE
BD Model09 Simulation I=1034A

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/bo-dipoles#2]
Booster dipole fieldmap at maximum current 

 bo-dipoles/model-09/simulation/2016-12-12_BD_Model09_Sim_X=-80_35mm_Z=-1000_1000mm_I=1034A.txt

**Comment by xresende** [comment]
multipoles around RK trajectory (@ 3.148425 GeV) are basically the same as for the nominal extraction energy.
maximum integrated dipolar field is 4.9% above nominal value corresponding to 3 GeV (close enough to spec 5.0%)
